### ISSUE TITLE
Адаптация компонента под тачскрины

### ISSUE THREAD

**Issue by arimanr** [sergant210/OrphoMan#1]
Хотелось бы увидеть активацию окна компонента не по "Ctrl+Enter", а по клику на Tooltip "Сообщить об ошибке", который появляется при выделении текста. 

Если возможно, хотелось бы увидеть предупреждение в случае выделения слишком малого или слишком большого куска текста. Что-нибудь вроде "Нужно выделить от n до m символов. Вы выделили слишком (большой/малый) отрывок".

P.S.: В порядке "а вот было бы совсем круто" - username отправителя если он зарегистрирован и авторизован на ресурсе.

Лично я планирую запретить гостям пользоваться компонентом, а оставить только для определенной группы пользователей. Вывести сниппет только для определенной группы - не проблема, а вот получить их  username хотелось бы. Если ковыряться самому то, это только замена вывода ip, а терять функцию не хочется, очень надеюсь, что появится "из коробки".

**Comment by sergant210** [comment]
> Хотелось бы увидеть активацию окна компонента не по "Ctrl+Enter", а по клику на Tooltip "Сообщить об ошибке", который появляется при выделении текста. 

 Сделано.

> Если возможно, хотелось бы увидеть предупреждение в случае выделения слишком малого или слишком большого куска текста. Что-нибудь вроде "Нужно выделить от n до m символов. Вы выделили слишком (большой/малый) отрывок".

Это работает из коробки.

> P.S.: В порядке "а вот было бы совсем круто" - username отправителя если он зарегистрирован и авторизован на ресурсе.
> Лично я планирую запретить гостям пользоваться компонентом, а оставить только для определенной группы пользователей. Вывести сниппет только для определенной группы - не проблема, а вот получить их username хотелось бы. Если ковыряться самому то, это только замена вывода ip, а терять функцию не хочется, очень надеюсь, что появится "из коробки".

Тут могу предложить использовать для этих целей поле "Комментарий".
